# Generated by Django 4.2.6 on 2024-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('attending', models.BooleanField()),
                ('dietary_restrictions', models.CharField(max_length=250, null=True)),
                ('accommodation_from', models.DateField(null=True)),
                ('accommodation_to', models.DateField(null=True)),
                ('drink_preferences', models.TextField()),
                ('song', models.CharField(max_length=100)),
            ],
        ),
    ]
